GET http://localhost:3001/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "blog 1",
    "author": "maryum",
    "url": "dfgdfgfgz",
    "likes": 10
}